[package]
name = "sei-cosmwasm"
version = "0.4.3"
edition = "2021"
description = "Bindings and helpers for cosmwasm contracts to interact with sei blockchain"
license = "Apache-2.0"
readme = "README.md"

[features]
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = "1.0.0"
schemars = "0.8.3"
serde = { version = "1.0.127", default-features = false, features = ["derive"] }
serde_repr = "0.1.8"

[dev-dependencies]
cosmwasm-schema = "1.0.0"
